// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agentApplicationService.proto

package com.yoozoo.protoconf.agent;

public final class AgentApplicationServiceOuterClass {
  private AgentApplicationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogonInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agentApplicationService.LogonInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * token is private key encrypted, can embed in code
     * including app_name, do we need serial_number for kicking out the invalid one?
     * </pre>
     *
     * <code>string app_token = 1;</code>
     */
    java.lang.String getAppToken();
    /**
     * <pre>
     * token is private key encrypted, can embed in code
     * including app_name, do we need serial_number for kicking out the invalid one?
     * </pre>
     *
     * <code>string app_token = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppTokenBytes();

    /**
     * <code>string env = 2;</code>
     */
    java.lang.String getEnv();
    /**
     * <code>string env = 2;</code>
     */
    com.google.protobuf.ByteString
        getEnvBytes();
  }
  /**
   * Protobuf type {@code agentApplicationService.LogonInfoRequest}
   */
  public  static final class LogonInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agentApplicationService.LogonInfoRequest)
      LogonInfoRequestOrBuilder {
    // Use LogonInfoRequest.newBuilder() to construct.
    private LogonInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogonInfoRequest() {
      appToken_ = "";
      env_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogonInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appToken_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              env_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgentApplicationServiceOuterClass.LogonInfoRequest.class, AgentApplicationServiceOuterClass.LogonInfoRequest.Builder.class);
    }

    public static final int APP_TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object appToken_;
    /**
     * <pre>
     * token is private key encrypted, can embed in code
     * including app_name, do we need serial_number for kicking out the invalid one?
     * </pre>
     *
     * <code>string app_token = 1;</code>
     */
    public java.lang.String getAppToken() {
      java.lang.Object ref = appToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * token is private key encrypted, can embed in code
     * including app_name, do we need serial_number for kicking out the invalid one?
     * </pre>
     *
     * <code>string app_token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppTokenBytes() {
      java.lang.Object ref = appToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENV_FIELD_NUMBER = 2;
    private volatile java.lang.Object env_;
    /**
     * <code>string env = 2;</code>
     */
    public java.lang.String getEnv() {
      java.lang.Object ref = env_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        env_ = s;
        return s;
      }
    }
    /**
     * <code>string env = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEnvBytes() {
      java.lang.Object ref = env_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        env_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appToken_);
      }
      if (!getEnvBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, env_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appToken_);
      }
      if (!getEnvBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, env_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgentApplicationServiceOuterClass.LogonInfoRequest)) {
        return super.equals(obj);
      }
      AgentApplicationServiceOuterClass.LogonInfoRequest other = (AgentApplicationServiceOuterClass.LogonInfoRequest) obj;

      boolean result = true;
      result = result && getAppToken()
          .equals(other.getAppToken());
      result = result && getEnv()
          .equals(other.getEnv());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APP_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAppToken().hashCode();
      hash = (37 * hash) + ENV_FIELD_NUMBER;
      hash = (53 * hash) + getEnv().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgentApplicationServiceOuterClass.LogonInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agentApplicationService.LogonInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agentApplicationService.LogonInfoRequest)
        AgentApplicationServiceOuterClass.LogonInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgentApplicationServiceOuterClass.LogonInfoRequest.class, AgentApplicationServiceOuterClass.LogonInfoRequest.Builder.class);
      }

      // Construct using com.yoozoo.protoconf.agent.AgentApplicationServiceOuterClass.LogonInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appToken_ = "";

        env_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoRequest_descriptor;
      }

      public AgentApplicationServiceOuterClass.LogonInfoRequest getDefaultInstanceForType() {
        return AgentApplicationServiceOuterClass.LogonInfoRequest.getDefaultInstance();
      }

      public AgentApplicationServiceOuterClass.LogonInfoRequest build() {
        AgentApplicationServiceOuterClass.LogonInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AgentApplicationServiceOuterClass.LogonInfoRequest buildPartial() {
        AgentApplicationServiceOuterClass.LogonInfoRequest result = new AgentApplicationServiceOuterClass.LogonInfoRequest(this);
        result.appToken_ = appToken_;
        result.env_ = env_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgentApplicationServiceOuterClass.LogonInfoRequest) {
          return mergeFrom((AgentApplicationServiceOuterClass.LogonInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgentApplicationServiceOuterClass.LogonInfoRequest other) {
        if (other == AgentApplicationServiceOuterClass.LogonInfoRequest.getDefaultInstance()) return this;
        if (!other.getAppToken().isEmpty()) {
          appToken_ = other.appToken_;
          onChanged();
        }
        if (!other.getEnv().isEmpty()) {
          env_ = other.env_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgentApplicationServiceOuterClass.LogonInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgentApplicationServiceOuterClass.LogonInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appToken_ = "";
      /**
       * <pre>
       * token is private key encrypted, can embed in code
       * including app_name, do we need serial_number for kicking out the invalid one?
       * </pre>
       *
       * <code>string app_token = 1;</code>
       */
      public java.lang.String getAppToken() {
        java.lang.Object ref = appToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * token is private key encrypted, can embed in code
       * including app_name, do we need serial_number for kicking out the invalid one?
       * </pre>
       *
       * <code>string app_token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppTokenBytes() {
        java.lang.Object ref = appToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * token is private key encrypted, can embed in code
       * including app_name, do we need serial_number for kicking out the invalid one?
       * </pre>
       *
       * <code>string app_token = 1;</code>
       */
      public Builder setAppToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * token is private key encrypted, can embed in code
       * including app_name, do we need serial_number for kicking out the invalid one?
       * </pre>
       *
       * <code>string app_token = 1;</code>
       */
      public Builder clearAppToken() {
        
        appToken_ = getDefaultInstance().getAppToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * token is private key encrypted, can embed in code
       * including app_name, do we need serial_number for kicking out the invalid one?
       * </pre>
       *
       * <code>string app_token = 1;</code>
       */
      public Builder setAppTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object env_ = "";
      /**
       * <code>string env = 2;</code>
       */
      public java.lang.String getEnv() {
        java.lang.Object ref = env_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          env_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string env = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEnvBytes() {
        java.lang.Object ref = env_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          env_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string env = 2;</code>
       */
      public Builder setEnv(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        env_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string env = 2;</code>
       */
      public Builder clearEnv() {
        
        env_ = getDefaultInstance().getEnv();
        onChanged();
        return this;
      }
      /**
       * <code>string env = 2;</code>
       */
      public Builder setEnvBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        env_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:agentApplicationService.LogonInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:agentApplicationService.LogonInfoRequest)
    private static final AgentApplicationServiceOuterClass.LogonInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgentApplicationServiceOuterClass.LogonInfoRequest();
    }

    public static AgentApplicationServiceOuterClass.LogonInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogonInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<LogonInfoRequest>() {
      public LogonInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogonInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogonInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogonInfoRequest> getParserForType() {
      return PARSER;
    }

    public AgentApplicationServiceOuterClass.LogonInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogonInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agentApplicationService.LogonInfoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user = 1;</code>
     */
    java.lang.String getUser();
    /**
     * <code>string user = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string endpoints = 3;</code>
     */
    java.lang.String getEndpoints();
    /**
     * <code>string endpoints = 3;</code>
     */
    com.google.protobuf.ByteString
        getEndpointsBytes();

    /**
     * <code>string app_name = 4;</code>
     */
    java.lang.String getAppName();
    /**
     * <code>string app_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();
  }
  /**
   * Protobuf type {@code agentApplicationService.LogonInfoResponse}
   */
  public  static final class LogonInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agentApplicationService.LogonInfoResponse)
      LogonInfoResponseOrBuilder {
    // Use LogonInfoResponse.newBuilder() to construct.
    private LogonInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogonInfoResponse() {
      user_ = "";
      password_ = "";
      endpoints_ = "";
      appName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogonInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              user_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              endpoints_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              appName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgentApplicationServiceOuterClass.LogonInfoResponse.class, AgentApplicationServiceOuterClass.LogonInfoResponse.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private volatile java.lang.Object user_;
    /**
     * <code>string user = 1;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <code>string user = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDPOINTS_FIELD_NUMBER = 3;
    private volatile java.lang.Object endpoints_;
    /**
     * <code>string endpoints = 3;</code>
     */
    public java.lang.String getEndpoints() {
      java.lang.Object ref = endpoints_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endpoints_ = s;
        return s;
      }
    }
    /**
     * <code>string endpoints = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEndpointsBytes() {
      java.lang.Object ref = endpoints_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endpoints_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object appName_;
    /**
     * <code>string app_name = 4;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      }
    }
    /**
     * <code>string app_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, user_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (!getEndpointsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endpoints_);
      }
      if (!getAppNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, user_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (!getEndpointsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endpoints_);
      }
      if (!getAppNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgentApplicationServiceOuterClass.LogonInfoResponse)) {
        return super.equals(obj);
      }
      AgentApplicationServiceOuterClass.LogonInfoResponse other = (AgentApplicationServiceOuterClass.LogonInfoResponse) obj;

      boolean result = true;
      result = result && getUser()
          .equals(other.getUser());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && getEndpoints()
          .equals(other.getEndpoints());
      result = result && getAppName()
          .equals(other.getAppName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + ENDPOINTS_FIELD_NUMBER;
      hash = (53 * hash) + getEndpoints().hashCode();
      hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgentApplicationServiceOuterClass.LogonInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agentApplicationService.LogonInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agentApplicationService.LogonInfoResponse)
        AgentApplicationServiceOuterClass.LogonInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgentApplicationServiceOuterClass.LogonInfoResponse.class, AgentApplicationServiceOuterClass.LogonInfoResponse.Builder.class);
      }

      // Construct using com.yoozoo.protoconf.agent.AgentApplicationServiceOuterClass.LogonInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        user_ = "";

        password_ = "";

        endpoints_ = "";

        appName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonInfoResponse_descriptor;
      }

      public AgentApplicationServiceOuterClass.LogonInfoResponse getDefaultInstanceForType() {
        return AgentApplicationServiceOuterClass.LogonInfoResponse.getDefaultInstance();
      }

      public AgentApplicationServiceOuterClass.LogonInfoResponse build() {
        AgentApplicationServiceOuterClass.LogonInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AgentApplicationServiceOuterClass.LogonInfoResponse buildPartial() {
        AgentApplicationServiceOuterClass.LogonInfoResponse result = new AgentApplicationServiceOuterClass.LogonInfoResponse(this);
        result.user_ = user_;
        result.password_ = password_;
        result.endpoints_ = endpoints_;
        result.appName_ = appName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgentApplicationServiceOuterClass.LogonInfoResponse) {
          return mergeFrom((AgentApplicationServiceOuterClass.LogonInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgentApplicationServiceOuterClass.LogonInfoResponse other) {
        if (other == AgentApplicationServiceOuterClass.LogonInfoResponse.getDefaultInstance()) return this;
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (!other.getEndpoints().isEmpty()) {
          endpoints_ = other.endpoints_;
          onChanged();
        }
        if (!other.getAppName().isEmpty()) {
          appName_ = other.appName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgentApplicationServiceOuterClass.LogonInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgentApplicationServiceOuterClass.LogonInfoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <code>string user = 1;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user = 1;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user = 1;</code>
       */
      public Builder clearUser() {
        
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>string user = 1;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endpoints_ = "";
      /**
       * <code>string endpoints = 3;</code>
       */
      public java.lang.String getEndpoints() {
        java.lang.Object ref = endpoints_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endpoints_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endpoints = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEndpointsBytes() {
        java.lang.Object ref = endpoints_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endpoints_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endpoints = 3;</code>
       */
      public Builder setEndpoints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endpoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endpoints = 3;</code>
       */
      public Builder clearEndpoints() {
        
        endpoints_ = getDefaultInstance().getEndpoints();
        onChanged();
        return this;
      }
      /**
       * <code>string endpoints = 3;</code>
       */
      public Builder setEndpointsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endpoints_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appName_ = "";
      /**
       * <code>string app_name = 4;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_name = 4;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_name = 4;</code>
       */
      public Builder clearAppName() {
        
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <code>string app_name = 4;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:agentApplicationService.LogonInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:agentApplicationService.LogonInfoResponse)
    private static final AgentApplicationServiceOuterClass.LogonInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgentApplicationServiceOuterClass.LogonInfoResponse();
    }

    public static AgentApplicationServiceOuterClass.LogonInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogonInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<LogonInfoResponse>() {
      public LogonInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogonInfoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogonInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogonInfoResponse> getParserForType() {
      return PARSER;
    }

    public AgentApplicationServiceOuterClass.LogonInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogonErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:agentApplicationService.LogonError)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string detail = 1;</code>
     */
    java.lang.String getDetail();
    /**
     * <code>string detail = 1;</code>
     */
    com.google.protobuf.ByteString
        getDetailBytes();
  }
  /**
   * Protobuf type {@code agentApplicationService.LogonError}
   */
  public  static final class LogonError extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:agentApplicationService.LogonError)
      LogonErrorOrBuilder {
    // Use LogonError.newBuilder() to construct.
    private LogonError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogonError() {
      detail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogonError(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              detail_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonError_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AgentApplicationServiceOuterClass.LogonError.class, AgentApplicationServiceOuterClass.LogonError.Builder.class);
    }

    public static final int DETAIL_FIELD_NUMBER = 1;
    private volatile java.lang.Object detail_;
    /**
     * <code>string detail = 1;</code>
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      }
    }
    /**
     * <code>string detail = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDetailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, detail_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDetailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, detail_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AgentApplicationServiceOuterClass.LogonError)) {
        return super.equals(obj);
      }
      AgentApplicationServiceOuterClass.LogonError other = (AgentApplicationServiceOuterClass.LogonError) obj;

      boolean result = true;
      result = result && getDetail()
          .equals(other.getDetail());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getDetail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AgentApplicationServiceOuterClass.LogonError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AgentApplicationServiceOuterClass.LogonError prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code agentApplicationService.LogonError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:agentApplicationService.LogonError)
        AgentApplicationServiceOuterClass.LogonErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonError_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AgentApplicationServiceOuterClass.LogonError.class, AgentApplicationServiceOuterClass.LogonError.Builder.class);
      }

      // Construct using com.yoozoo.protoconf.agent.AgentApplicationServiceOuterClass.LogonError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        detail_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AgentApplicationServiceOuterClass.internal_static_agentApplicationService_LogonError_descriptor;
      }

      public AgentApplicationServiceOuterClass.LogonError getDefaultInstanceForType() {
        return AgentApplicationServiceOuterClass.LogonError.getDefaultInstance();
      }

      public AgentApplicationServiceOuterClass.LogonError build() {
        AgentApplicationServiceOuterClass.LogonError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AgentApplicationServiceOuterClass.LogonError buildPartial() {
        AgentApplicationServiceOuterClass.LogonError result = new AgentApplicationServiceOuterClass.LogonError(this);
        result.detail_ = detail_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AgentApplicationServiceOuterClass.LogonError) {
          return mergeFrom((AgentApplicationServiceOuterClass.LogonError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AgentApplicationServiceOuterClass.LogonError other) {
        if (other == AgentApplicationServiceOuterClass.LogonError.getDefaultInstance()) return this;
        if (!other.getDetail().isEmpty()) {
          detail_ = other.detail_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AgentApplicationServiceOuterClass.LogonError parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AgentApplicationServiceOuterClass.LogonError) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object detail_ = "";
      /**
       * <code>string detail = 1;</code>
       */
      public java.lang.String getDetail() {
        java.lang.Object ref = detail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          detail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string detail = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDetailBytes() {
        java.lang.Object ref = detail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          detail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string detail = 1;</code>
       */
      public Builder setDetail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        detail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string detail = 1;</code>
       */
      public Builder clearDetail() {
        
        detail_ = getDefaultInstance().getDetail();
        onChanged();
        return this;
      }
      /**
       * <code>string detail = 1;</code>
       */
      public Builder setDetailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        detail_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:agentApplicationService.LogonError)
    }

    // @@protoc_insertion_point(class_scope:agentApplicationService.LogonError)
    private static final AgentApplicationServiceOuterClass.LogonError DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AgentApplicationServiceOuterClass.LogonError();
    }

    public static AgentApplicationServiceOuterClass.LogonError getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogonError>
        PARSER = new com.google.protobuf.AbstractParser<LogonError>() {
      public LogonError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogonError(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogonError> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogonError> getParserForType() {
      return PARSER;
    }

    public AgentApplicationServiceOuterClass.LogonError getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agentApplicationService_LogonInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agentApplicationService_LogonInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agentApplicationService_LogonInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agentApplicationService_LogonInfoResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_agentApplicationService_LogonError_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_agentApplicationService_LogonError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035agentApplicationService.proto\022\027agentAp" +
      "plicationService\"2\n\020LogonInfoRequest\022\021\n\t" +
      "app_token\030\001 \001(\t\022\013\n\003env\030\002 \001(\t\"X\n\021LogonInf" +
      "oResponse\022\014\n\004user\030\001 \001(\t\022\020\n\010password\030\002 \001(" +
      "\t\022\021\n\tendpoints\030\003 \001(\t\022\020\n\010app_name\030\004 \001(\t\"\034" +
      "\n\nLogonError\022\016\n\006detail\030\001 \001(\t2\202\001\n\027AgentAp" +
      "plicationService\022g\n\014getLogonInfo\022).agent" +
      "ApplicationService.LogonInfoRequest\032*.ag" +
      "entApplicationService.LogonInfoResponse\"" +
      "\000B\026\n\024com.yoozoo.protoconfb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_agentApplicationService_LogonInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_agentApplicationService_LogonInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agentApplicationService_LogonInfoRequest_descriptor,
        new java.lang.String[] { "AppToken", "Env", });
    internal_static_agentApplicationService_LogonInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_agentApplicationService_LogonInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agentApplicationService_LogonInfoResponse_descriptor,
        new java.lang.String[] { "User", "Password", "Endpoints", "AppName", });
    internal_static_agentApplicationService_LogonError_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_agentApplicationService_LogonError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_agentApplicationService_LogonError_descriptor,
        new java.lang.String[] { "Detail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
